name: Deploy Flask App

on:
  workflow_dispatch:

  

jobs:
  deploy:
    runs-on: self-hosted

    env: 
      DOCKER_HUB_USERNAME: ${{ vars.DOCKER_USERNAME }}
      
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          docker compose up -d --build
            
          