name: Deploy Flask App

on:
   workflow_run:
    workflows: [ "Docker Build and Push"]
    types:
       - completed
    branches: [main]
    

  

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    env: 
      DOCKER_HUB_USERNAME: ${{ vars.DOCKER_USERNAME }}
      
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      -  name: Set up Docker Compose
         uses: docker/setup-compose-action@v2

      -  name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v4

      - name: Deploy with Docker Compose
        run: |
           docker compose -f dockercompose.yml down --rmi all --volumes --remove-orphans
           docker compose -f dockercompose.yml build --no-cache
           docker compose -f dockercompose.yml up -d
            
          